<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class ProductUnit extends Model
{
    protected $fillable = [
        'product_id',
        'product_variation_id',
        'serial_number',
        'condition',
        'status',
        'purchase_date',
        'purchase_price',
        'residual_value',
        'useful_life',
        'notes',
        'last_checked_at',
        'maintenance_status',
    ];

    protected $casts = [
        'purchase_date' => 'date',
        'purchase_price' => 'decimal:2',
        'residual_value' => 'decimal:2',
        'useful_life' => 'integer',
        'last_checked_at' => 'datetime',
    ];

    public const STATUS_AVAILABLE = 'available';
    public const STATUS_SCHEDULED = 'scheduled';
    public const STATUS_RENTED = 'rented';
    public const STATUS_MAINTENANCE = 'maintenance';
    public const STATUS_RETIRED = 'retired';

    public function product(): BelongsTo
    {
        return $this->belongsTo(Product::class);
    }

    public function variation(): BelongsTo
    {
        return $this->belongsTo(ProductVariation::class, 'product_variation_id');
    }

    public function kits(): HasMany
    {
        return $this->hasMany(UnitKit::class, 'unit_id');
    }

    public function rentalItems(): HasMany
    {
        return $this->hasMany(RentalItem::class);
    }

    public function carts(): HasMany
    {
        return $this->hasMany(Cart::class);
    }

    public function maintenanceRecords(): HasMany
    {
        return $this->hasMany(MaintenanceRecord::class);
    }

    public function getCurrentValueAttribute(): float
    {
        $cost = $this->purchase_price ?? 0;
        if ($cost == 0) return 0;
        
        $residual = $this->residual_value ?? 0;
        $lifeMonths = $this->useful_life ?? 60;
        $purchaseDate = $this->purchase_date;
        
        if (!$purchaseDate) return $cost;
        
        // Calculate full months passed
        $ageMonths = $purchaseDate->diffInMonths(now());
        
        if ($ageMonths >= $lifeMonths) {
            return $residual;
        }
        
        $depreciableAmount = $cost - $residual;
        $monthlyDepreciation = $depreciableAmount / $lifeMonths;
        $depreciation = $monthlyDepreciation * $ageMonths;
        
        return max($residual, round($cost - $depreciation, 2));
    }

    public static function getStatusOptions(): array
    {
        return [
            self::STATUS_AVAILABLE => 'Available',
            self::STATUS_SCHEDULED => 'Scheduled',
            self::STATUS_RENTED => 'Rented',
            self::STATUS_MAINTENANCE => 'Maintenance',
            self::STATUS_RETIRED => 'Retired',
        ];
    }

    public static function getStatusColor(string $status): string
    {
        return match ($status) {
            self::STATUS_AVAILABLE => 'success',
            self::STATUS_SCHEDULED => 'primary',
            self::STATUS_RENTED => 'warning',
            self::STATUS_MAINTENANCE => 'info',
            self::STATUS_RETIRED => 'danger',
            default => 'gray',
        };
    }

    public static function getConditionOptions(): array
    {
        return [
            'excellent' => 'Excellent',
            'good' => 'Good',
            'fair' => 'Fair',
            'poor' => 'Poor',
            'broken' => 'Broken',
            'lost' => 'Lost',
        ];
    }

    /**
     * Refresh unit status based on rentals and conditions
     */
    public function refreshStatus(): void
    {
        // If status is RETIRED, don't auto-change it
        if ($this->status === self::STATUS_RETIRED) {
            return;
        }

        $newStatus = self::STATUS_AVAILABLE;

        // Check if currently rented
        $activeRental = $this->rentalItems()
            ->whereHas('rental', function ($query) {
                $query->whereIn('status', [
                    Rental::STATUS_ACTIVE,
                    Rental::STATUS_LATE_RETURN
                ]);
            })
            ->exists();

        if ($activeRental) {
            $newStatus = self::STATUS_RENTED;
        } else {
            // Check if in maintenance
            $maintenance = $this->maintenanceRecords()
                ->whereIn('status', ['pending', 'in_progress'])
                ->exists();
            
            if ($maintenance) {
                $newStatus = self::STATUS_MAINTENANCE;
            }
        }

        if ($this->status !== $newStatus) {
            $this->update(['status' => $newStatus]);
        }
    }

    /**
     * Calculate total revenue generated by this unit
     */
    public function calculateTotalRevenue(): float
    {
        return $this->rentalItems()
            ->whereHas('rental', function ($query) {
                $query->whereNotIn('status', [Rental::STATUS_CANCELLED]);
            })
            ->sum('subtotal');
    }

    /**
     * Calculate total maintenance cost
     */
    public function calculateTotalMaintenanceCost(): float
    {
        return $this->maintenanceRecords()->sum('cost');
    }

    /**
     * Calculate profitability (Revenue - Maintenance - Purchase Price)
     */
    public function calculateProfitability(): float
    {
        $revenue = $this->calculateTotalRevenue();
        $maintenance = $this->calculateTotalMaintenanceCost();
        $cost = $this->purchase_price ?? 0;

        return $revenue - $maintenance - $cost;
    }

    /**
     * Update status based on rental activity
     */
    public function updateStatusBasedOnRentals()
    {
        $newStatus = $this->status;

        // Check for active rentals (Rented)
        $isRented = $this->rentalItems()
            ->whereHas('rental', function ($query) {
                $query->whereIn('status', [Rental::STATUS_ACTIVE, Rental::STATUS_LATE_RETURN]);
            })->exists();

        if ($isRented) {
            $newStatus = self::STATUS_RENTED;
        } else {
            // If status is MAINTENANCE, we only change it if it's rented (handled above)
            // Otherwise we keep it as MAINTENANCE until manually changed
            if ($this->status === self::STATUS_MAINTENANCE) {
                return;
            }

            // Check for scheduled rentals
            $isScheduled = $this->rentalItems()
                ->whereHas('rental', function ($query) {
                    $query->whereIn('status', [Rental::STATUS_QUOTATION, Rental::STATUS_CONFIRMED, Rental::STATUS_LATE_PICKUP]);
                })->exists();

            if ($isScheduled) {
                $newStatus = self::STATUS_SCHEDULED;
            } else {
                // If not rented and not scheduled, it's available
                $newStatus = self::STATUS_AVAILABLE;
            }
        }

        // Only update if status changed to avoid loops/unnecessary queries
        if ($this->status !== $newStatus) {
            $this->update(['status' => $newStatus]);
        }
    }
}